# configure auto-configured MultipartConfigElement
multipart:
  maxFileSize: 50MB
  maxRequestSize: 50MB
  location: ${java.io.tmpdir}

spring:
  mvc:
    favicon:
      enabled: false
  dao:
    exceptiontranslation:
      enabled: false

server:
  port: 8080

debug: true

#logging:
#  level.: DEBUG

com:
  justgifit:
    optimize: true
    git-location: ${java.io.tmpdir}/git
    optimize-level-2: true

